services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll-nsp
    volumes:
      - .:/srv/jekyll
    ports:
      - "4001:4000"
    command: sh -c "jekyll serve --watch --host 0.0.0.0"

